wrappid/native-web

.github/workflows/pr-guardrails.yml
package-lock.json

add pr-guardrails config
Ref: #13

ci: :wrench: add pr-guardrails

---

.eslintrc.js
LICENSE
package-lock.json
package.json

added MIT License as requested
Ref #16

docs: 🔒 license added

---

package.json

update main branch from development

update main branch

---

lint-staged.config.js
package.json

update eslint scripts
Ref: #13

ci(config): :wrench: update linting scripts

---

package-lock.json
package.json
package/package-lock.json
package/package.json

add missing keys, author, license, in package.json
Ref: wrappid/native-mobile#36

docs(config): :memo: add missing keys in package.json

---

package-lock.json
package.json
package/package-lock.json
package/package.json
scripts/attributions.gen.js

Merge development branch into main branch

Merge development into main

---

package/nativeComponents/inputs/NativeOtpInput.js

import React from "react" in NativeOtpInput.js, which was getting undefined.
ref: #26

fix: :bug: Import React in NativeComponents.js file which was undefined

---

package/nativeComponents/dataDisplay/NativeIcon.js

color props was not working for Icon component
ref: #33

fix: :bug: add color props in Nativecon

---

package/index.js

coreContainer not rendering issue resolved in native-web
ref: #42

fix(global): :ambulance: coreContainer not rendering issue resolved

---

package/index.js
package/nativeComponents/feedback/NativeNetworkStatus.js
package/nativeComponents/feedback/NativeOnlineStatusSnackbar.js

onlineStatusSnackbar removed from core and added to native package in native-web
ref: #45

enhancement: onlineStatusSnackbar removed from core and added to native-web

---

package/index.js

import issue resolved in index js for native web network status
ref: #45

fix(core): :bug: import issue resolved in index js

---

package/styledComponents/navigation/SCDrawer.js
package/styledComponents/navigation/SCRightDrawer.js

enhancement: removing getConfigurationObject and replace it with WrappidData
Ref #51

fix(core): :zap: replace getConfigurationObject with WrappidData

---

package/nativeComponents/inputs/NativeButton.js
package/nativeComponents/layouts/NativeAppContainer.js
package/nativeComponents/surfaces/NativeCard.js

refactor(core): ♻️ correct 'OnClick' to 'onClick' props
Ref #55

refactor(core): ♻️ correct 'OnClick' to 'onClick' props

---

package/nativeComponents/surfaces/NativeDrawer.js
package/styledComponents/navigation/SCDrawer.js

pass config as props to SCDrawer
Ref #55

fix(core): :bricks: pass config as props

---

package/nativeComponents/layouts/NativeAppContainer.js

correct styleClasses props
ref: #55

fix(core): :bug: correct styleClasses props

---

package/nativeComponents/dataDisplay/NativeIcon.js

icons spacing related bug fixed
ref: #55

fix(core): :bug: icons spacing related bug fixed

---

package/nativeComponents/inputs/NativeImagePicker.js

fix NativeImagePicker upload
Ref: #67

fix: :bug: fix NativeImagePicker upload

---

package/nativeComponents/feedback/NativeDialog.js

onClose fix in NativeDialog
Ref: #67

fix(global): :bug: onClose fix in NativeDialog

---

package/nativeComponents/navigation/NativeTabHead.js

**Description**
handling styleComponents props passed from CoreTabHead, in NativeTabHead
ref: #74

fix(core): :bug: styleComponents props handling in NativeTabHead

---

package-lock.json
package.json
package/package-lock.json
package/package.json
package/styledComponents/inputs/SCDatePicker.js

mui/x-date-pickers version change  to 5.0.8
Ref: #63

fix(global): :wrench: mui/x-date-pickers version change

---

package/nativeComponents/inputs/NativeJSONEditor.js

native json editor fixed
Ref #78

fix(core): :bug: native json editor fixed

---

package/nativeComponents/inputs/NativeOtpInput.js

Deleting a character directly without selecting it first. Pasting the OTP using Ctrl+V
ref: #82

fix(core): :bug: update code in NativeOtpInput to fix the issue

---

package/nativeComponents/inputs/NativeImagePicker.js

change NativeImagePicker tooltip message to `Upload Image` from `Change Image` message
Ref: #86

style(utils): :art: change NativeImagePicker tooltip message

---

package/nativeComponents/inputs/NativeOtpInput.js

add if check in useEffect of otp
Ref: #84

fix(core): :bug: otp undefiend
